// <auto-generated />
using ApiAuth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiAuth.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250710053805_Initials")]
    partial class Initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("ApiAuth.Models.User", b =>
                {
                    b.Property<int>("usr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("usr_email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("usr_password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("usr_user_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("usr_id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
